### ISSUE TITLE
Complete homepage

### ISSUE THREAD

**Issue by wouterraateland** [WISVCH/symposium-2018#6]
- [x] #1 Create intro section
- [x] #2 Create partners section
- [ ] #3 Create CvA section
- [x] #4 Create RvA section
- [ ] #5 Create Committee section
- [ ] #7 Update contact / routes section

**Comment by wouterraateland** [comment]
There should be some space or some other information between the intro section and the partners section. For both better information flow and visual balance.
